import Head from "next/head";
import styles from "../styles/Home.module.scss";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Calls Redirect</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="preload" href="/fonts/AvertaDemo/AvertaDemo-Regular.otf" as="font" crossOrigin="" />
				<link rel="preload" href="/fonts/AvertaDemo/AvertaDemo-Regular.otf" as="font" crossOrigin="" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<img className={styles.bgImg} src="/image 2.png" alt="" />
				<div className={styles.imageLayer} />
				<nav className={styles.nav}>
					<img src="/Logo.png" alt="" />
					<div className={styles.menuBtn}>
						<p>menu</p>
						<div className={styles.lines}>
							<div />
							<div />
						</div>
					</div>
				</nav>

				<div className={styles.banner}>
					<div>
						<h1>
							Get your Corporate <span>Phone Number</span> Today.
						</h1>
						<p>
							We provide your business to have a cloud-based centralised communication service allowing
							your users to communicate & collaborate in a way more inherent way.
						</p>
						<button>GET IT NOW</button>
					</div>
				</div>
			</main>

			<div className={styles.section1}>
				<h1>We are Available for</h1>

				<div className={styles.info}>
					<div className={styles.infoCards}>
						<img src="/rocket.svg" alt="" />
						<div>
							<p>Startups</p>
							<p>Learn More</p>
						</div>
					</div>
					<div className={styles.infoCards}>
						<img src="/suitcase.svg" alt="" />
						<div>
							<p>Startups</p>
							<p>Learn More</p>
						</div>
					</div>
					<div className={styles.infoCards}>
						<img src="/building.svg" alt="" />
						<div>
							<p>Startups</p>
							<p>Learn More</p>
						</div>
					</div>
				</div>

				<h1>Search your number</h1>
				<p>Search our broad inventory and access thousands of local or toll free phone numbers instantly</p>
			</div>

			<div className={styles.searchBox}>
				<div className={styles.imageLayer} />
				<img src="/keyboard.png" alt="" />
				<div>
					<div className={styles.inputs}>
						<div>
							<p>Select Country</p>
							<p>United States</p>
						</div>
						<div>
							<p>Enter Area code</p>
							<p>881</p>
						</div>
					</div>
					<button>Search</button>
				</div>
			</div>

			<div className={styles.section2}>
				<div className={styles.features}>
					<h1>All features</h1>
					<img src="/laptop.png" alt="" />
				</div>
				<div className={styles.customers}>
					<h1>our Beloved customers</h1>
					<div className={styles.customerReview}>
						<img src="/customer.png" alt="" />
						<div>
							<p>
								“ The customer service of CallsRedirect is great. I spoke to Clara and she was very
								fantastic. She setup several advanced features for our new numbers. I highly recommend “
							</p>
							<p>- Cyrille S. CEO, onfleeck.com</p>
						</div>
					</div>
					<div className={styles.btns}>
						<img src="/leftArrow.png" alt="" />
						<img src="/rightArrow.png" alt="" />
					</div>
				</div>
			</div>

			<footer className={styles.footer}>
				<div>
					<div className={styles.left}>
						<div className={styles.links}>
							<a href="#">home</a>
							<a href="#">Features</a>
							<a href="#">Support</a>
							<a href="#">terms of use</a>
							<a href="#">about us</a>
							<a href="#">career</a>
						</div>
						<p>contact@callsredirect.com</p>
						<p>Call us : +1-888-803-0060</p>
						<div className={styles.policies}>
							<p>Privacy policy</p>
							<p>terms of use</p>
						</div>
						<div>
							<p>© Copyright 2021 CallsRedirect. All Rights Reserved</p>
						</div>
					</div>
					<div className={styles.right}>
						<p>Why be shy</p>
						<p>say hi.</p>
						<div className={styles.socialLinks}>
							<p>
								LinkedIn
								<img src="/linkedin.png" alt="" />
							</p>
							<p>
								Twitter
								<img src="/twitter.png" alt="" />
							</p>
						</div>
						<div>
							<img src="/hasprLogo.png" alt="" />
							<p>haspr </p>
							<p>design and engineering</p>
							<p>www.haspr.in</p>
						</div>
					</div>
				</div>
			</footer>
		</div>
	);
}
